time:
  start: 24       # h
  stop: 48        # h
  step: 12       # h

temperature:
  start_c: 100   # °C
  stop_c: 120    # °C
  step_c: 10      # °C

bake_profile:
  start_C: 25.0           # °C
  ramp_rate_C_per_min: 1.0  # °C/min (same as K/min)

initial:
  u0: 1000.0    # at.%·nm
  v0: 10.0      # at.%·nm

grid:
  x_max_nm: 1000.0   # spatial domain [0, x_max], in nm
  n_x:     2001      # number of spatial grid points
  t_steps: 3001      # number of time‐grid points (solver resolution)
