time:
  start: 6    # h
  stop: 6     # h
  step: 1       # h

temperature:
  start_c: 120  # °C
  stop_c: 120   # °C
  step_c: 1     # °C

initial:
  u0: 1000.0    # at.%·nm
  v0: 10.0      # at.%·nm

grid:
  x_max_nm: 1000.0   # spatial domain [0, x_max], in nm
  n_x:     2001      # number of spatial grid points
  t_steps: 3001      # number of time‐grid points (solver resolution)
