time:
  start_h: 24         # start time (h)
  stop_h: 24         # stop time (h)
  step_h: 1          # time step (h)

temperature:
  start_C: 120.0      # start temp (°C)
  stop_C: 120.0      # stop temp (°C)
  step_C: 1.0        # temp step (°C)

temp_profile:
  start_C: 25.0             # initial temp for profile (°C)
  ramp_rate_C_per_min: 1.0  # ramp rate (°C/min)
  cooling_time_h: 3.0       # cooling time (h)
  tol_K: 1.0                # cooling stop tolerance (K)
  two_step:
    t1_C: 75.0       # first‐step peak temp (°C)
    bake1_h: 4.0    # hold time at t1_C (h)
    t2_C: 120.0      # second‐step peak temp (°C)
    bake2_h: 48.0    # hold time at t2_C (h)

grid:
  x_max_nm: 1000.0   # maximum depth (nm)
  n_x: 2001          # spatial grid points
  n_t: 3001          # time grid points

initial:
  u0: 1000 #189.5    # initial total oxygen per unit area from Nb205 (at.%·nm)
  v0: 10 # 5.08      # initial total amount of oxygen (at.%·nm)
  base_O: 0.005  # initial base oxygen concentration (at.%)
  lambda_0_nm: 27.0        # clean‐limit penetration depth (nm)

ciovati:
  D:
    D_0: 0.0138     # diffusion prefactor (cm^2 /s)
    E_A: 111530.0       # activation energy (eV)(J·mol⁻¹) 
  k:
    A: !!float 3.0e9        # reaction prefactor (1/s)
    E_A: 135000.0        # activation energy (eV) (J·mol⁻¹) 
  u0: 1000.0    # initial u-parameter (at.%·nm)
  v0: 10.0      # initial v-parameter (at.%·nm)
  c0: 0.0       # initial concentration (at.%)
  
output:
  directory: sim_output    # where to save CSVs & plots

args:
  applied_field_mT: 100.0   # applied magnetic field (mT)
  dead_layer_nm: 0      # dead‐layer thickness (nm)
  demag_factor: 0        # demagnetization factor (unitless)
